[[section-building-block-view]]
== Building Block View

This section describes the PlantUML Plugin modules which you will also find in the
Java package structure.

=== Level 1

The following UML package diagram shows the main building blocks of the system and their interdependencies:

["plantuml","MainBuildingBlocks","png"]
-----
skinparam package {
    FontSize 20
    FontColor #42788e
    BorderColor black
    BorderColor black
    BackgroundColor #D5F3FF
}
skinparam packageStyle frame
skinparam ArrowFontName Impact
skinparam ArrowColor #42788e
skinparam ArrowFontColor #42788e

package de.kontext_e.demo.facade <<Entry Point>> {
}

together {
    package de.kontext_e.demo.business {}
    package de.kontext_e.demo.core {}
    package de.kontext_e.demo.exporter {}
    package de.kontext_e.demo.importer {}
}
together {
    package de.kontext_e.demo.cache {}
    package de.kontext_e.demo.manager {}
    package de.kontext_e.demo.parser {}
    package de.kontext_e.demo.processor {}
}


de.kontext_e.demo.processor ---> de.kontext_e.demo.exporter

de.kontext_e.demo.facade ---> de.kontext_e.demo.processor
de.kontext_e.demo.facade ---> de.kontext_e.demo.parser
de.kontext_e.demo.facade ---> de.kontext_e.demo.exporter
de.kontext_e.demo.facade ---> de.kontext_e.demo.manager
de.kontext_e.demo.facade ---> de.kontext_e.demo.cache
de.kontext_e.demo.facade ---> de.kontext_e.demo.business
de.kontext_e.demo.facade ---> de.kontext_e.demo.core

de.kontext_e.demo.parser ---> de.kontext_e.demo.importer
de.kontext_e.demo.parser ---> de.kontext_e.demo.core

de.kontext_e.demo.exporter ---> de.kontext_e.demo.core

de.kontext_e.demo.manager ---> de.kontext_e.demo.core

de.kontext_e.demo.importer ---> de.kontext_e.demo.core

de.kontext_e.demo.core -right-> de.kontext_e.demo.business

-----

.Description of de.kontext_e.demo packages
[options="header"]
|====
| Package       | Purpose
| business      | Definition of some business classes and rules
| cache         | Cache some computed results
| core          | The core functionality
| exporter      | Export data into a file
| facade        | Published Interface for clients
| importer      | Import data from a file
| manager       | Manages some stuff
| parser        | Parses imported data
| processor     | Process data before export
|====


==== Known Technical Debt

*Unwanted Dependencies*

During the lifetime many features were added. For some of them, a building block needs information stored in
a different building block or has to call functionality of another building block - but these new connections
lead to circular dependencies. To keep the System maintainable, the architecture must be improved:
resolve dependency circles, move responsibilities etc. Open tasks are:

.Unwantend Module Dependencies
[options="header"]
|===
| From                          | To                          | What should be done
| de.kontext_e.demo.business    | de.kontext_e.demo.core      | Because ...; Todo: ...
| de.kontext_e.demo.exporter    | de.kontext_e.demo.facade    | Because ...; Todo: ...
| de.kontext_e.demo.exporter    | de.kontext_e.demo.processor | Because ...; Todo: ...
| de.kontext_e.demo.importer    | de.kontext_e.demo.parser    | Because ...; Todo: ...
|===

